version: '3'
services:
  web:
    container_name: fan
    build: .
    image: fumi00hiro/fan
    working_dir: /code
    ports:
      - 3000:3000
      - 8000:8000
      - 8080:8080
    volumes:
      - .:/code
    tty: true
    depends_on:
      - db
  db:
    container_name: fan-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci && --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
